package com.sasmac.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-28T15:30:45.446+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "FileCopy", 
                  wsdlLocation = "http://localhost:8081/FileCopy/ws/CopyService?wsdl",
                  targetNamespace = "http://webservices.sasmac.com/") 
public class FileCopy extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservices.sasmac.com/", "FileCopy");
    public final static QName FileCopyPort = new QName("http://webservices.sasmac.com/", "FileCopyPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/FileCopy/ws/CopyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FileCopy.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/FileCopy/ws/CopyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FileCopy(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileCopy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileCopy() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns FileCopyPortType
     */
    @WebEndpoint(name = "FileCopyPort")
    public FileCopyPortType getFileCopyPort() {
        return super.getPort(FileCopyPort, FileCopyPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileCopyPortType
     */
    @WebEndpoint(name = "FileCopyPort")
    public FileCopyPortType getFileCopyPort(WebServiceFeature... features) {
        return super.getPort(FileCopyPort, FileCopyPortType.class, features);
    }

}
