package com.sasmac.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.11 2017-04-28T09:07:12.355+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "FileCopyService", wsdlLocation = "http://localhost:8081/FileCopy/ws/CopyService?wsdl", targetNamespace = "http://webservices.sasmac.com/")
public class FileCopyService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName(
			"http://webservices.sasmac.com/", "FileCopyService");
	public final static QName FileCopyServerPort = new QName(
			"http://webservices.sasmac.com/", "FileCopyServerPort");
	static {
		URL url = null;
		try {
			url = new URL("http://localhost:8081/FileCopy/ws/CopyService?wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger
					.getLogger(FileCopyService.class.getName())
					.log(java.util.logging.Level.INFO,
							"Can not initialize the default wsdl from {0}",
							"http://localhost:8081/FileCopy/ws/CopyService?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public FileCopyService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public FileCopyService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FileCopyService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns FileCopy
	 */
	@WebEndpoint(name = "FileCopyServerPort")
	public FileCopy getFileCopyServerPort() {
		return super.getPort(FileCopyServerPort, FileCopy.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns FileCopy
	 */
	@WebEndpoint(name = "FileCopyServerPort")
	public FileCopy getFileCopyServerPort(WebServiceFeature... features) {
		return super.getPort(FileCopyServerPort, FileCopy.class, features);
	}

}
