package com.sasmac.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11 2017-04-28T15:30:45.386+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://webservices.sasmac.com/", name = "FileCopyPortType")
@XmlSeeAlso({ ObjectFactory.class })
public interface FileCopyPortType {

	@WebMethod(operationName = "CopyFtoF")
	@RequestWrapper(localName = "CopyFtoF", targetNamespace = "http://webservices.sasmac.com/", className = "com.sasmac.service.CopyFtoF")
	@ResponseWrapper(localName = "CopyFtoFResponse", targetNamespace = "http://webservices.sasmac.com/", className = "com.sasmac.service.CopyFtoFResponse")
	@WebResult(name = "return", targetNamespace = "http://webservices.sasmac.com/")
	public int copyFtoF(
			@WebParam(name = "arg0", targetNamespace = "http://webservices.sasmac.com/") java.lang.String arg0,
			@WebParam(name = "arg1", targetNamespace = "http://webservices.sasmac.com/") java.lang.String arg1);

	@WebMethod
	@RequestWrapper(localName = "filetransaction", targetNamespace = "http://webservices.sasmac.com/", className = "com.sasmac.service.Filetransaction")
	@ResponseWrapper(localName = "filetransactionResponse", targetNamespace = "http://webservices.sasmac.com/", className = "com.sasmac.service.FiletransactionResponse")
	@WebResult(name = "return", targetNamespace = "http://webservices.sasmac.com/")
	public int filetransaction(
			@WebParam(name = "arg0", targetNamespace = "http://webservices.sasmac.com/") java.lang.String arg0,
			@WebParam(name = "arg1", targetNamespace = "http://webservices.sasmac.com/") java.lang.String arg1);
}
